<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>false</PublishSingleFile>
    <AssemblyName>SekiroParamMerger</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SekiroParamMerger.Core\SekiroParamMerger.Core.csproj" />
  </ItemGroup>

</Project>